PUT  http://localhost:8080/events/1
content-type: application/json

{

    "name": "Test event updated",
    "description": "A test event 1 got updated",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}